CREATE TABLE public.avaliacao (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    livro_id bigint NOT NULL,
    nota numeric(4,2) NOT NULL,
    comentario character varying(500)
);

ALTER TABLE public.avaliacao OWNER TO postgres;

ALTER TABLE public.avaliacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avaliacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.favorito (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    livro_id bigint NOT NULL
);

ALTER TABLE public.favorito OWNER TO postgres;

ALTER TABLE public.favorito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.livro (
    id bigint NOT NULL,
    ano_publicacao character varying(255),
    autor character varying(255),
    disponivel boolean NOT NULL,
    titulo character varying(255)
);

ALTER TABLE public.livro OWNER TO postgres;

ALTER TABLE public.livro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.livro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.multa (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    livro_id bigint NOT NULL,
    valor numeric(4,2) NOT NULL,
    status character varying(1) NOT NULL,
    data_geracao date NOT NULL,
    data_pagamento date
);

ALTER TABLE public.multa OWNER TO postgres;

ALTER TABLE public.multa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.multa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);

ALTER TABLE public.usuario OWNER TO postgres;

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT avaliacao_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT avaliacao_usuario_id_livro_id_key UNIQUE (usuario_id, livro_id);

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT favorito_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT favorito_usuario_id_livro_id_key UNIQUE (usuario_id, livro_id);

ALTER TABLE ONLY public.livro
    ADD CONSTRAINT livro_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.multa
    ADD CONSTRAINT multa_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);

CREATE INDEX livro_id ON public.avaliacao USING btree (livro_id);

CREATE INDEX usuario_id ON public.avaliacao USING btree (usuario_id);

CREATE INDEX livro_id ON public.favorito USING btree (livro_id);

CREATE INDEX usuario_id ON public.favorito USING btree (usuario_id);

CREATE INDEX livro_id ON public.multa USING btree (livro_id);

CREATE INDEX usuario_id ON public.multa USING btree (usuario_id);

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT avaliacao_livro_id_fkey FOREIGN KEY (livro_id) REFERENCES public.livro(id) MATCH FULL;

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT avaliacao_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) MATCH FULL;

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT favorito_livro_id_fkey FOREIGN KEY (livro_id) REFERENCES public.livro(id) MATCH FULL;

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT favorito_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) MATCH FULL;

ALTER TABLE ONLY public.multa
    ADD CONSTRAINT multa_livro_id_fkey FOREIGN KEY (livro_id) REFERENCES public.livro(id) MATCH FULL;

ALTER TABLE ONLY public.multa
    ADD CONSTRAINT multa_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) MATCH FULL;
